language: php
sudo: true
php
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.2
      env: DEPENDENCIES='dev' SYMFONY_VERSION='3.4.*@dev'
    - php: 7.2
      env: SYMFONY_VERSION='4.4.*@dev'

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install: composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit