services:
  Saloodo\Scheduler\Jobs\Mutex\SchedulerLocker:
    public: true
    arguments:
        - 'scheduler.cache_driver'
        -
  Saloodo\Scheduler\Jobs\Mutex\SchedulerSymfonyLocker:
    public: true
    arguments:
      - 'scheduler.cache_store'

  Saloodo\Scheduler\Jobs\Mutex\JobLocker:
    public: true
    arguments:
        - 'scheduler.cache_driver'

  Saloodo\Scheduler\Jobs\Mutex\JobSymfonyLocker:
    public: true
    arguments:
      - 'scheduler.cache_store'

  Saloodo\Scheduler\Jobs\Scheduler:
    public: true
    arguments:
      - '@event_dispatcher'
      - '@Saloodo\Scheduler\Jobs\Mutex\SchedulerSymfonyLocker'
      - '@Saloodo\Scheduler\Jobs\Mutex\JobSymfonyLocker'

  Saloodo\Scheduler\Command\ListCommand:
    arguments:
      - '@service_container'
    tags: ['console.command']

  Saloodo\Scheduler\Command\RunCommand:
      arguments:
        - '@Saloodo\Scheduler\Jobs\Scheduler'
        - '@event_dispatcher'
        - '%kernel.environment%'
      tags: ['console.command']
